# Generated by Django 2.2 on 2019-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
