# Generated by Django 2.2 on 2019-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0004_auto_20190507_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_PROBLEMS',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/uploads/')),
                ('status', models.CharField(max_length=100)),
                ('worker_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='PROBLEMS',
        ),
    ]
