# Generated by Django 2.2 on 2019-05-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0008_auto_20190509_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMP_REPORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/uploads/completed/')),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WORKER_REPORT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/uploads/completed/')),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='all_problems',
            old_name='date',
            new_name='completion_date',
        ),
        migrations.AddField(
            model_name='all_problems',
            name='report_date',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
