# Generated by Django 2.2 on 2019-05-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0009_auto_20190509_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ALL_PROBLEMS',
            new_name='ALL_PROBLEMS1',
        ),
    ]
